name: Release

on:
  workflow_dispatch:
    inputs:
      force-version:
        description: "Force specific version (leave empty for automatic)"
        required: false
        type: string

jobs:
  release:
    name: Create Release
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          FORCE_VERSION: ${{ inputs.force-version }}
        run: |
          npx semantic-release
